version: '3'

services:
  jupyterlab:
    build: .
    image: data_analysis
    volumes:
      - ./:/project
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
    command: start-notebook.sh
